
@hostname = localhost
@port = {{$dotenv PORT}}
@host = {{hostname}}:{{port}}
@vehicle_id = {{create_vehicle.response.body.data.id}}

@user_id = {{create_user.response.body.data.id}}

### Get all
GET http://{{host}}/api/vehicles/

### Create
# @name create_vehicle
POST http://{{host}}/api/vehicles/?user={{user_id}}
Content-Type: application/json

{
  "type":"EV",
  "make":"Hyundai",
  "model":"Kona",
  "commissioned": true,
  "license_plate": "ABC-123"
}

### Get single
GET http://{{host}}/api/vehicles/{{vehicle_id}}

### Modify
PUT http://{{host}}/api/vehicles/{{vehicle_id}}

### Delete vehicle entry
DELETE http://{{host}}/api/vehicles/{{vehicle_id}}

### Get all users
GET http://{{host}}/api/users/

### Create user
# @name create_user
POST http://{{host}}/api/users/
Content-Type: application/json

{
  "name": "Testi Ukko",
  "username":"Testiukko"
}
