import type { Metadata } from "next";
import Link from "next/link";
import "./globals.css";
import styles from "./layout.module.css";

export const metadata: Metadata = {
  title: "Fake Shop Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        {/* Header */}
        <div className={styles.header}>
          <h2>THE FAKE STORE</h2>
          <p>Fake store rest API for your e-commerce or shopping prototype</p>

          {/* "Navbar" */}
          <nav>
            <div>
              <Link href="/">Home</Link>
            </div>
            <div>
              <Link href="/products">Products</Link>
            </div>
            <div>
              <Link href="/about">About</Link>
            </div>
          </nav>
        </div>

        {/* Renders the page */}
        <div>{children}</div>
      </body>
    </html>
  );
}
